---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  #- name: centos-6.4

suites:
- name: default
  run_list:
  - recipe[dse-cassandra-test::default]
  attributes:
    dse-cassandra-test:
      url: https://<%= ENV['DSE_CASSANDRA_USERNAME'] %>:<%= ENV['DSE_CASSANDRA_PASSWORD'] %>@downloads.datastax.com/enterprise/dse-4.0.3-bin.tar.gz